// Code generated by protoc-gen-go.
// source: checkrtt.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	checkrtt.proto
	test.proto

It has these top-level messages:
	CheckRtt
	Test
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckRtt struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Time             *int64 `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CheckRtt) Reset()                    { *m = CheckRtt{} }
func (m *CheckRtt) String() string            { return proto.CompactTextString(m) }
func (*CheckRtt) ProtoMessage()               {}
func (*CheckRtt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CheckRtt) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CheckRtt) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckRtt)(nil), "example.CheckRtt")
}

func init() { proto.RegisterFile("checkrtt.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x48, 0x4d,
	0xce, 0x2e, 0x2a, 0x29, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x55, 0xd2, 0xe3, 0xe2, 0x70, 0x06, 0x49, 0x05, 0x95, 0x94, 0x08, 0xf1, 0x71,
	0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71,
	0xb1, 0x94, 0x64, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x69, 0x30, 0x07, 0x81, 0xd9, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa6, 0x46, 0x01, 0x1e, 0x49, 0x00, 0x00, 0x00,
}
